### ISSUE TITLE
Please reduce the image size

### ISSUE THREAD

**Issue by IanSun** [ntkme/systemd-podman#9]
Current image is too large.  It needs more time to be downloaded and uses a lot of storage.

The problem is that, you make a package [update](https://github.com/ntkme/systemd-podman/blob/cab6e0283d563b36c9528918c4da7cd6425cb7d2/Dockerfile#L9) in the build stage. This doesn't actually make the packages in the image are updated. To achieve that, you could watch the base image update, and trigger a new build stage when the base image is updated.

**Comment by ntkme** [comment]
The current difference on x86_64 for running an update is 249MB vs 291MB. It's not that much. Getting the latest packages is for security reasons as fedora never updates the base image after they cut a major release, only rpm repo is updated. 

The proper way to save this 42MB if you are concerned is not ignoring the updates but to squash all the image layers (including base layer) into one. However, it's bad for layer reusability thus not recommended - it may reduce disk footprint if the base layer is only used in once in all the images you have on a registry, but if you have multiple images on a registry or your local machine that shares the same base image layer, squashing the base layer wil cost more spaces overall.

Therefore, I would not make any changes to the current image, however, you can squash it on your end if you're truly concerned:

1. Create a `Containerfile`

``` dockerfile
FROM ghcr.io/ntkme/systemd-podman:edge
```

2. Run `podman build --squash-all -t update-squash-all .`

```
REPOSITORY                                 TAG         IMAGE ID      CREATED         SIZE
localhost/update-squash-all                latest      72d4d84c1c1d  9 minutes ago   253 MB
localhost/no-update                        latest      bfa68f276b32  10 minutes ago  249 MB
localhost/update                           latest      0e1d5cffbdd7  11 minutes ago  291 MB
```
